# Site settings
baseURL = "http://jenchen1398.github.io/"
languageCode = "en-us"
title = "Jenny Chen: Student, Developer, Violinist"
theme = "forty"
publicDir = "jenchen1398.github.io"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Jenny Chen"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = ["css/my.css"]
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Jenny Chen"
    subtitle = "Student, Developer, Violinist"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"
      
    [[params.navigation.links]]
      name = "Portfolio"
      url = "#one"
      
    [[params.navigation.links]]
      name = "About"
      url = "#two"
    
    [[params.navigation.links]]
      name = "Contact"
      url = "#footer"
      
    # Button Style 2
    # [[params.navigation.button2]]
      # name = "Blog"
      # url = "blog"
      
 

    

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"
    


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Jenny"
    subtitle = "Student, Developer, Violinist"
    buttonText = "About Me"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Music Style Transfer"
      subtitle = "" #"Ipsum Dolor Sit Amet"
      image = 'img/blog/cat.jpg'
      url = "blog/music-style"

    [[params.tiles.showcase]]
      title = "Studying & Traveling in Spain"
      subtitle = "" #"Feugiat Amet Tempus"
      image = 'acoruna.jpg'
      url = "blog/spain"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more information take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "I am an undergraduate student studying CS and music at Columbia University"
    subtitle1 = """I love finding ways in which technology itself can be stretched to new limits when integrated with other fields.  I've researched feature engineering in deep convolutional neural nets and style transfer in artistic media (music). At Columbia, I'm the President of Columbia Classical Performers and am a member of ADI."""
    
    subtitle2 = """As a violinist, I've been invited to perform at Carnegie Hall as 1st place winner of the American Protégé International Concerto Competition and as a trio in the Columbia Chamber Players. I've served as co-concertmaster of the Idyllwild Arts Orchestra and was a violinist at the Aspen Music Festival. In San Diego, I founded the Music Outreach Club and led a team of 30 people to provide free music education & therapy, and hosted benefit concerts to raise over $5000 for charities (Coffee 4 Kids Honduras & Liberty in North Korea). I currently study violin with Stefan Jackiw on scholarship from the Columbia Dolan Prize."""
    buttonText = "Read My Blog"
    url = "blog"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "jc4686@columbia.edu"
    
    [[params.contact.github]]
    title = "Github"
    github = "github.com/jenchen1398"

     [[params.contact.linkedin]]
    title = "Linkedin"
    linkedin = "linkedin.com/in/jc4686"
    
  # Footer section
  [params.footer]
    enable = true
    copyright = "Jenny Chen 2018"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
